production:
  email_delivery:
    email_delivery:
      delivery_method: :smtp
      smtp_settings:
        enable_starttls_auto: true
        address: smtp.gmail.com
        port: 587
        domain: smtp.gmail.com
        authentication: :plain
        user_name: minnotec.aiom@gmail.com
        password: Mit82589155
